### ISSUE TITLE
schema name is fixed to 'scott' in the .ps and .pb scripts

### ISSUE THREAD

**Issue by GasparYYC** [connormcd/audit_utility#3]
Hi,
At the top of the script:
audit_utility/same_schema/audit_util_pb.sql 
and 
audit_utility/same_schema/audit_util_ps.sql the define schema = scott
define tspace = users
define prefix = aud$

I think thats a leftover from a previous testing.

**Comment by connormcd** [comment]
That is by design so that people can run *just* the package if they already have the audit tables etc already set up.

The setup script does explicitly say:

pro Have you set the SCHEMA and TSPACE variables before running this?
pro If yes, press Enter to continue, otherwise Ctrl-C to abort

I'll edit the text to try make it a bit clearer
